import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/app/componets/Navbar";
import Footer from "@/app/componets/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="container mx-auto px-4">
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
